kumuluzee:
  name: restaurant-catalog
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/RestaurantCatalogDS
      connection-url: jdbc:postgresql://localhost:5432/restaurantcatalog
      username: postgres
      password: postgres
      pool:
        max-size: 3
  health:
    servlet:
      mapping: /health/live
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/RestaurantCatalogDS
    metrics:
      web-instrumentation:
        - name: restaurants-endpoint
          url-pattern: /v1/restaurants/*
rest-properties:
  maintenance-mode: false
  broken: false